/**
 * The daily-question pool. Both phones pick deterministically by date, and
 * answers stay hidden until both are in — so write answers, not replies.
 */
export const DAILY_QUESTIONS: string[] = [
  'What small thing made you smile today?',
  'What do you miss most about being in the same room right now?',
  'What song would you play for me tonight, and why?',
  'What did you almost text me today but didn’t?',
  'When did you last feel really proud of me?',
  'What’s something I do that instantly calms you down?',
  'If we had three hours together tonight, no travel needed — what would we do?',
  'What’s a tiny detail about me you hope never changes?',
  'What was the hardest moment of your day, in one sentence?',
  'What are you looking forward to most about our next visit?',
  'What’s something you’ve wanted to ask me but keeps slipping away?',
  'Which of our memories do you revisit the most?',
  'What did you eat today, and what would you rather have eaten with me?',
  'What’s one thing you’re quietly worried about this week?',
  'When today did you think of me without any reason?',
  'What’s a place you walked past recently and thought: I want to show them this?',
  'What compliment do you secretly wish I’d give you more often?',
  'If tonight had a color, what color is it for you — and why?',
  'What’s something new you learned or noticed today?',
  'What part of your day would have been better with me in it?',
  'What’s a smell or sound that reminded you of me lately?',
  'What do you want more of in your life right now?',
  'What’s one thing you forgive yourself for today?',
  'If you could teleport to me for ten minutes right now, what would we do?',
  'What’s the last thing that made you laugh out loud?',
  'What’s a fear about us you’ve never said out loud?',
  'What are you most tired of explaining to other people?',
  'What would you cook for us if I arrived hungry in an hour?',
  'When did you feel closest to me this week?',
  'What’s one thing about your day-to-day life I probably can’t picture accurately?',
  'What’s something you admire about how I handle hard things?',
  'What tiny ritual should we invent, just for the two of us?',
  'What’s the most alive you’ve felt in the past month?',
  'What did your younger self dream about that still matters to you?',
  'If we wrote a book together, what would it be about?',
  'What’s something you want us to try on our next visit?',
  'What’s one way I could support you better from far away?',
  'What made you feel loved most recently?',
  'What’s a question you wish someone would ask you?',
  'Which photo of us is your favorite right now, and why?',
  'What’s something small you’re saving up to tell me in person?',
  'If today was a weather report of your heart, what was the forecast at noon?',
  'What habit of mine did you find annoying at first but love now?',
  'What’s something you’re getting better at, even if nobody notices?',
  'What would a perfect lazy Sunday together look like?',
  'What’s the bravest thing you did this week, however small?',
  'What do you hope we’re doing exactly one year from today?',
  'What’s a conversation topic we haven’t explored yet?',
  'When do you feel most beautiful or handsome?',
  'What’s one thing distance has actually taught you about us?',
  'What would you want me to whisper to you right before you fall asleep tonight?',
  'What’s something ordinary that felt special today?',
  'Who in your life deserves a thank-you they haven’t gotten?',
  'What’s the first thing you want to do when we close the distance for good?',
  'What made you choose me — the real moment, not the polite answer?',
  'What’s one thing you need this week that you haven’t asked for?',
  'If our relationship had a soundtrack this month, which song is track one?',
  'What tiny thing about your room or view do you wish I could see right now?',
  'What’s something you’d like us to celebrate that isn’t a typical occasion?',
  'What part of yourself have you been neglecting lately?',
];

/**
 * Monthly "Future Question" prompts — written to your future selves,
 * sealed for three months. Indexed by month, shared by both partners.
 */
export const LETTER_PROMPTS: string[] = [
  'Write to us three months from now: what do you hope has changed, and what do you hope is exactly the same?',
  'Describe today’s version of your love in detail — the texture of it — so future-you can compare.',
  'What are you afraid of right now? Tell your future self, who already knows how it turned out.',
  'Make three small predictions about us. Be brave with at least one of them.',
  'What do you want to thank your partner for — dated today, read in a season?',
  'Describe the next visit before it happens. When it’s unsealed, compare it to what really happened.',
  'What is a promise you’re ready to make today, for future-you to check on?',
  'Write down a dream for us that feels slightly too big to say out loud.',
  'What do you love about your own life right now, separate from us? Future-you will want to remember.',
  'What is the hardest part of the distance this month? Tell it to the person who has already survived it.',
  'Describe your partner as if introducing them to a stranger — the version of them you see this month.',
  'If the next three months go the way you hope, what will we be laughing about when this unseals?',
];
